name: nap_nest
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6 
  svg_flutter: ^0.0.1
  intl: ^0.20.2
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.17
  dots_indicator: ^4.0.1
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  linear_progress_bar: ^1.1.3
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter_steps: ^1.0.5
  audioplayers: ^6.4.0
  fl_chart: ^1.0.0
  flutter_animate: ^4.5.2



dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Regular.ttf
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-SemiBold.ttf
          weight: 600
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/static/Lora-Regular.ttf
        - asset: assets/fonts/Lora/static/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora/static/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lora/static/Lora-SemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter_28pt-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter_native_splash:
  color: "#77B5FE"
  image: assets/images/app_logo.png
  branding: assets/images/app_icon.png
  android: true
  ios: true
  fullscreen: true

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null


flutter_intl:
  enabled: true
